name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        run: |
          docker build -t angular-frontend:latest -f angular-frontend/Dockerfile ./angular-frontend

  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        run: |
          docker build -t fastapi-backend:latest -f fastapi-backend/Dockerfile ./fastapi-backend

  test-frontend:
    name: Test Frontend in Docker
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Frontend Tests
        run: |
          docker run --rm angular-frontend:latest npm test -- --watch=false

  test-backend:
    name: Test Backend in Docker
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Backend Tests
        run: |
          docker run --rm fastapi-backend:latest pytest fastapi-backend

  deploy:
    name: Deploy Locally
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]

    steps:
      - name: Deploy Frontend and Backend
        run: |
          echo "Frontend Docker Image: angular-frontend:latest"
          echo "Backend Docker Image: fastapi-backend:latest"
          echo "Simulating deployment process..."
