name: Build, Test, and Deploy with Docker Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers for Frontend
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-frontend
          key: ${{ runner.os }}-docker-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-frontend-

      - name: Build Frontend Docker Image
        run: |
          docker buildx build \
            --cache-to=type=local,dest=/tmp/.buildx-cache-frontend \
            --cache-from=type=local,src=/tmp/.buildx-cache-frontend \
            -t angular-frontend:latest \
            -f angular-frontend/Dockerfile ./angular-frontend

      - name: List Docker Images
        run: docker images

      - name: Save Frontend Docker Image as Artifact
        run: |
          docker save angular-frontend:latest | gzip > angular-frontend.tar.gz
        shell: bash

      - name: Upload Frontend Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: angular-frontend-image
          path: angular-frontend.tar.gz

  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers for Backend
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-backend
          key: ${{ runner.os }}-docker-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-backend-

      - name: Build Backend Docker Image
        run: |
          docker buildx build \
            --cache-to=type=local,dest=/tmp/.buildx-cache-backend \
            --cache-from=type=local,src=/tmp/.buildx-cache-backend \
            -t fastapi-backend:latest \
            -f fastapi-backend/Dockerfile ./fastapi-backend

      - name: List Docker Images
        run: docker images

      - name: Save Backend Docker Image as Artifact
        run: |
          docker save fastapi-backend:latest | gzip > fastapi-backend.tar.gz
        shell: bash

      - name: Upload Backend Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-backend-image
          path: fastapi-backend.tar.gz
